# Introdução à biblioteca Numpy

NumPy, que significa **Numerical Python**, é uma das bibliotecas mais importantes para a Computação Científica em Python. Ela fornece suporte para arrays e matrizes multidimensionais, juntamente com uma vasta coleção de funções matemáticas para operações com essas estruturas.


## Por que NumPy?

- **Desempenho**: Implementado em C, oferece operações computacionais rápidas em arrays.

- **Facilidade de Uso**: Suporta uma ampla gama de operações com sintaxe clara e concisa.

- **Funcionalidade**: Vasta coleção de funções e métodos para processamento numérico.

## Importando NumPy

Para começar a usar o NumPy, você precisa importá-lo:

In [7]:
import numpy as np

Para mostrar a diferença de desempenho entre uma operação simples utilizando numPy e python

In [8]:
my_arr = np.arange(1000000)

my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 31.2 ms
Wall time: 19 ms


CPU times: total: 828 ms
Wall time: 829 ms


# Arrays NumPy

O coração do NumPy é o objeto array, que encapsula n-dimensões arrays de tipos de dados homogêneos, com muitas operações sendo realizadas em código compilado para desempenho.

## Criação de Arrays

Existem várias maneiras de criar arrays em NumPy:
- A partir de listas ou tuplas Python.
- Usando funções geradoras, como `arange`, `linspace`, etc.
- Através de funções dedicadas para criar arrays com valores iniciais, como `zeros`, `ones`, etc.

### Exemplos

In [9]:
# Criando um array a partir de uma lista
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [10]:
# Criando um array de zeros
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Array de uns
ones_array = np.ones((3, 2))
print(" Array de uns 3x2:\n", ones_array)

 Array de uns 3x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
# Criando um array com um intervalo de valores
range_arr = np.arange(10)
print(range_arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# Array espaçado linearmente
linspace_array = np.linspace(0, 1, 5)
print("Array espaçado linearmente:", linspace_array)

Array espaçado linearmente: [0.   0.25 0.5  0.75 1.  ]


# Operações com Arrays

NumPy fornece uma ampla variedade de operações matemáticas. As operações com arrays são elementares, o que significa que são aplicadas elemento a elemento. Algumas funções são feitas utilizando apenas um array e são chamadas de "ufuncs" enquanto outras precisam de dois arrays e são chamadas de "binary functions"

## Aritmética com Arrays

Você pode facilmente realizar adição, subtração, multiplicação e divisão com arrays:

In [14]:
# Adição
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


A mesma soma pode ser feita utilizando binary functions

In [15]:
np.add(a,b)

array([5, 7, 9])

In [16]:
# Subtração
print("Subtração:", a - b)

Subtração: [-3 -3 -3]


In [17]:
# Multiplicação elemento a elemento
print(a * b)

[ 4 10 18]


In [18]:
# Divisão
print("Divisão:", a / b)

Divisão: [0.25 0.4  0.5 ]


### Funções Matemáticas

NumPy oferece funções matemáticas que podem ser aplicadas diretamente aos arrays:

In [19]:
# Raiz quadrada
print("Raiz quadrada de a: ",np.sqrt(a),'\n')

# Seno
print("Seno de a: ",np.sin(a),'\n')

#Cosseno
print("Cosseno de a: ",np.cos(a),'\n')

Raiz quadrada de a:  [1.         1.41421356 1.73205081] 

Seno de a:  [0.84147098 0.90929743 0.14112001] 

Cosseno de a:  [ 0.54030231 -0.41614684 -0.9899925 ] 



### Agregações

Funções de agregação como `sum`, `mean`, `max`, `min` são usadas para resumir informações sobre o array:

In [20]:
# Soma dos elementos
print("Soma dos elementos de a: ",np.sum(a))

# Máximo elemento
print("Máximo elemento em a: ",np.max(a))

Soma dos elementos de a:  6
Máximo elemento em a:  3


### Ordenação

Podemos utilizar a função `sort` para ordernar um array

In [21]:
data = [6.2, 7.5, 8, 0, 1]
np.sort(data)

array([0. , 1. , 6.2, 7.5, 8. ])

### Lógicas de conjuntos

O NumPy tem algumas operações básicas de conjunto para
ndarrays unidimensionais

In [22]:
data = [6.2, 1, 2, 3, 0, 7.5, 8, 0, 1]
np.unique(data)

array([0. , 1. , 2. , 3. , 6.2, 7.5, 8. ])

# Indexação, Fatiamento e Iteração

Arrays NumPy suportam indexação, fatiamento e iteração, semelhantes às listas Python, mas com muito mais poder.

## Indexação

Você pode acessar elementos individuais de um array:

In [23]:
# Acessando o primeiro elemento
print(a[0])

1


## Indexação Booleana

In [24]:
# Cria um array de amostra
data = np.array([1, 2, 3, 4, 5])

In [25]:
# Cria um filtro booleano
filter = data > 3
print("Filtro:", filter)

Filtro: [False False False  True  True]


In [26]:
# Aplica o filtro
print("Dados filtrados:", data[filter])

Dados filtrados: [4 5]


Podemos utilizar a indexação booleana e acoplar com as funções vistas anteriormente para criar testes:

In [27]:
# Número de valores maior ou igual a 3 no array data
(data >= 3).sum()

3

## Fatiamento

Arrays podem ser fatiados usando a sintaxe `[inicio:fim:passo]`:

In [28]:
# Fatiando um array
print(a[0:2])

[1 2]


## Fatiamento Multidimensional

In [29]:
# Cria um array 2D
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Fatiamento
slice = data[:2, 1:3]
print("Fatia do array:\n", slice)

Fatia do array:
 [[2 3]
 [5 6]]


## Iteração

Arrays NumPy podem ser iterados usando loops `for`:

In [30]:
# Iterando sobre cada elemento
for element in a:
    print(element)

1
2
3


# Manipulação de Forma e Tamanho

NumPy oferece várias maneiras de alterar a forma e o tamanho dos arrays, permitindo a realização de operações complexas.

## Mudança de Forma

Você pode alterar a forma de um array sem alterar seus dados:

In [31]:
# Reshape de um array para 2x2
arr = np.arange(4)
reshaped_arr = arr.reshape((2, 2))
print(reshaped_arr)

[[0 1]
 [2 3]]


## Empilhamento e Divisão
Arrays podem ser empilhados verticalmente ou horizontalmente e divididos em vários arrays menores:

In [32]:
# Empilhamento horizontal
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
hstack = np.hstack((a, b))
print(hstack)

# Divisão
split_arr = np.split(hstack, 3)
print(split_arr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


# Álgebra Linear

NumPy fornece suporte a operações de álgebra linear, como produto de matrizes, determinantes, solução de sistemas lineares e muito mais.

## Produto de Matrizes

Você pode realizar o produto de matrizes usando `np.dot()` ou o operador `@`:

In [33]:
# Produto de matrizes
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)

[[19 22]
 [43 50]]


Utilizando o `numpy.linalg` é possível realizar outras funções algébricas

In [34]:
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)

-2.0000000000000004

In [35]:
from numpy.linalg import inv

inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Por hoje é só!

## Próximos Passos:

- Experimente os conceitos aprendidos praticando bastante.
- Explore a documentação oficial do `NumPy` para se aprofundar ainda mais.

Lembre-se, a prática é a chave para se tornar proficiente em qualquer habilidade. Continue explorando e utilizando o `NumPy` para resolver problemas reais de computação científica.